ADVANCEMENT_NAMES = {
    # Story advancements
    "minecraft:story/root": "Getting Wood",
    "minecraft:story/mine_stone": "Stone Age",
    "minecraft:story/upgrade_tools": "Getting an Upgrade",
    "minecraft:story/smelt_iron": "Acquire Hardware",
    "minecraft:story/obtain_armor": "Suit Up",
    "minecraft:story/lava_bucket": "Hot Stuff",
    "minecraft:story/iron_tools": "Isn't It Iron Pick",
    "minecraft:story/deflect_arrow": "Not Today, Thank You",
    "minecraft:story/form_obsidian": "Ice Bucket Challenge",
    "minecraft:story/mine_diamond": "Diamonds!",
    "minecraft:story/enter_the_nether": "We Need to Go Deeper",
    "minecraft:story/shiny_gear": "Cover Me with Diamonds",
    "minecraft:story/enchant_item": "Enchanter",
    "minecraft:story/cure_zombie_villager": "Zombie Doctor",
    "minecraft:story/follow_ender_eye": "Eye Spy",
    "minecraft:story/enter_the_end": "The End?",
    
    # Adventure advancements
    "minecraft:adventure/root": "Adventure",
    "minecraft:adventure/voluntary_exile": "Voluntary Exile",
    "minecraft:adventure/spyglass_at_parrot": "Is It a Bird?",
    "minecraft:adventure/spyglass_at_ghast": "Is It a Balloon?",
    "minecraft:adventure/spyglass_at_dragon": "Is It a Plane?",
    "minecraft:adventure/kill_a_mob": "Monster Hunter",
    "minecraft:adventure/kill_all_mobs": "Monsters Hunted",
    "minecraft:adventure/totem_of_undying": "Postmortal",
    "minecraft:adventure/summon_iron_golem": "Hired Help",
    "minecraft:adventure/trade": "What a Deal!",
    "minecraft:adventure/honey_block_slide": "Sticky Situation",
    "minecraft:adventure/ol_betsy": "Ol' Betsy",
    "minecraft:adventure/lightning_rod_with_villager_no_fire": "Surge Protector",
    "minecraft:adventure/fall_from_world_height": "Caves & Cliffs",
    "minecraft:adventure/salvage_sherd": "Respecting the Remnants",
    "minecraft:adventure/avoid_vibration": "Sneak 100",
    "minecraft:adventure/sleep_in_bed": "Sweet Dreams",
    "minecraft:adventure/hero_of_the_village": "Hero of the Village",
    "minecraft:adventure/throw_trident": "A Throwaway Joke",
    "minecraft:adventure/shoot_arrow": "Take Aim",
    "minecraft:adventure/kill_mob_near_sculk_catalyst": "It Spreads",
    "minecraft:adventure/adventuring_time": "Adventuring Time",
    "minecraft:adventure/play_jukebox_in_meadows": "Sound of Music",
    "minecraft:adventure/walk_on_powder_snow_with_leather_boots": "Light as a Rabbit",
    "minecraft:adventure/spyglass_at_dragon": "Is It a Plane?",
    "minecraft:adventure/very_very_frightening": "Very Very Frightening",
    "minecraft:adventure/sniper_duel": "Sniper Duel",
    "minecraft:adventure/bullseye": "Bullseye",
    
    # Nether advancements
    "minecraft:nether/root": "Nether",
    "minecraft:nether/return_to_sender": "Return to Sender",
    "minecraft:nether/find_bastion": "Those Were the Days",
    "minecraft:nether/obtain_ancient_debris": "Hidden in the Depths",
    "minecraft:nether/fast_travel": "Subspace Bubble",
    "minecraft:nether/find_fortress": "A Terrible Fortress",
    "minecraft:nether/obtain_crying_obsidian": "Who is Cutting Onions?",
    "minecraft:nether/distract_piglin": "Oh Shiny",
    "minecraft:nether/ride_strider": "This Boat Has Legs",
    "minecraft:nether/uneasy_alliance": "Uneasy Alliance",
    "minecraft:nether/loot_bastion": "War Pigs",
    "minecraft:nether/use_lodestone": "Country Lode, Take Me Home",
    "minecraft:nether/netherite_armor": "Cover Me in Debris",
    "minecraft:nether/get_wither_skull": "Spooky Scary Skeleton",
    "minecraft:nether/obtain_blaze_rod": "Into Fire",
    "minecraft:nether/charge_respawn_anchor": "Not Quite \"Nine\" Lives",
    "minecraft:nether/ride_strider_in_overworld_lava": "Feels Like Home",
    "minecraft:nether/explore_nether": "Hot Tourist Destinations",
    "minecraft:nether/summon_wither": "Withering Heights",
    "minecraft:nether/brew_potion": "Local Brewery",
    "minecraft:nether/create_beacon": "Bring Home the Beacon",
    "minecraft:nether/all_potions": "A Furious Cocktail",
    "minecraft:nether/create_full_beacon": "Beaconator",
    "minecraft:nether/all_effects": "How Did We Get Here?",
    
    # End advancements
    "minecraft:end/root": "The End",
    "minecraft:end/kill_dragon": "Free the End",
    "minecraft:end/dragon_egg": "The Next Generation",
    "minecraft:end/enter_end_gateway": "Remote Getaway",
    "minecraft:end/respawn_dragon": "The End... Again...",
    "minecraft:end/dragon_breath": "You Need a Mint",
    "minecraft:end/find_end_city": "The City at the End of the Game",
    "minecraft:end/elytra": "Sky's the Limit",
    "minecraft:end/levitate": "Great View From Up Here",
    
    # Husbandry advancements
    "minecraft:husbandry/root": "Husbandry",
    "minecraft:husbandry/safely_harvest_honey": "Bee Our Guest",
    "minecraft:husbandry/breed_an_animal": "The Parrots and the Bats",
    "minecraft:husbandry/ride_a_boat_with_a_goat": "Whatever Floats Your Goat!",
    "minecraft:husbandry/tame_an_animal": "Best Friends Forever",
    "minecraft:husbandry/make_a_sign_glow": "Glow and Behold!",
    "minecraft:husbandry/fishy_business": "Fishy Business",
    "minecraft:husbandry/silk_touch_nest": "Total Beelocation",
    "minecraft:husbandry/tadpole_in_a_bucket": "Bukkit Bukkit",
    "minecraft:husbandry/obtain_netherite_hoe": "Serious Dedication",
    "minecraft:husbandry/balanced_diet": "A Balanced Diet",
    "minecraft:husbandry/obtain_sniffer_egg": "Little Sniffs",
    "minecraft:husbandry/feed_snifflet": "Planting the Past",
    "minecraft:husbandry/plant_seed": "A Seedy Place",
    "minecraft:husbandry/wax_on": "Wax On",
    "minecraft:husbandry/wax_off": "Wax Off",
    "minecraft:husbandry/axolotl_in_a_bucket": "The Cutest Predator",
    "minecraft:husbandry/froglights": "With Our Powers Combined!",
    "minecraft:husbandry/complete_catalogue": "A Complete Catalogue",
    "minecraft:husbandry/tactical_fishing": "Tactical Fishing",
    "minecraft:husbandry/leash_all_frog_variants": "When the Squad Hops into Town",
    "minecraft:husbandry/allay_deliver_item_to_player": "You've Got a Friend in Me",
    "minecraft:husbandry/allay_deliver_cake_to_note_block": "Birthday Song",
}
